Frontends/ECommerce.WebUI/Areas/Admin/Controllers/ProductDetailController.cs
using ECommerce.DtoLayer.CatalogDtos.ProductDetailDtos;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace ECommerce.WebUI.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Route("Admin/ProductDetail")]
	public class ProductDetailController : Controller
	{
		private readonly IHttpClientFactory _httpClientFactory;

		public ProductDetailController(IHttpClientFactory httpClientFactory)
		{
			_httpClientFactory = httpClientFactory;
		}


		[Route("UpdateProductDetail/{id}")]
		[HttpGet]
		public async Task<IActionResult> UpdateProductDetail(string id)
		{
			
			ViewBag.v1 = "Ana Sayfa";
			ViewBag.v2 = "Ürün Açıklamaları";
			ViewBag.v3 = "Ürün Açıklama ve Bİlgi Sayfası";
			ViewBag.v0 = "Ürün Açıklama ve Bİlgi İşlemleri";
			var client = _httpClientFactory.CreateClient();
			var responseMessage = await client.GetAsync($"http://localhost:7081/api/ProductDetails/ProductDetailsByProductId?id={id}");

			if (responseMessage.IsSuccessStatusCode)
			{
				var jsonData = await responseMessage.Content.ReadAsStringAsync();
				var value = JsonConvert.DeserializeObject<UpdateProductDetailDto>(jsonData);
				if (value is null)
					return RedirectToAction("CreateProductDetail", new { id });
				return View(value);
			}
			return View();
		}
		[Route("UpdateProductDetail/{id}")]
		[HttpPost]
		public async Task<IActionResult> UpdateProductDetail(UpdateProductDetailDto updateProductDetailDto )
		{
			var client = _httpClientFactory.CreateClient();
			var jsonData = JsonConvert.SerializeObject(updateProductDetailDto);
			StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");
			var responseMessage = await client.PutAsync("http://localhost:7081/api/ProductDetails", stringContent);
			if (responseMessage.IsSuccessStatusCode)
			{
				return RedirectToAction("ProductListWithCategory", "Product", new { area = "Admin" });
			}
			return View();
		}






		[Route("CreateProductDetail/{id}")]
		[HttpGet]
		public async Task<IActionResult> CreateProductDetail(string id)
		{
			ViewBag.v1 = "Ana Sayfa";
			ViewBag.v2 = "Ürün Açıklamaları";
			ViewBag.v3 = "Ürün Açıklama ve Bİlgi Ekleme Sayfası";
			ViewBag.v0 = "Ürün Açıklama ve Bİlgi İşlemleri";

			var model = new CreateProductDetailDto
			{
				ProductId = id
			};

			return View(model);


		}


		[Route("CreateProductDetail/{id}")]
		[HttpPost]
		public async Task<IActionResult> CreateProductDetail(CreateProductDetailDto createProductDetailDto)
		{
			var client = _httpClientFactory.CreateClient();
			var jsonData = JsonConvert.SerializeObject(createProductDetailDto);
			StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");
			var responseMessage = await client.PostAsync("http://localhost:7081/api/ProductDetails", stringContent);
			if (responseMessage.IsSuccessStatusCode)
				return RedirectToAction("ProductListWithCategory", "Product", new { area = "Admin" });
			return View();
		}
	}
}

Frontends/ECommerce.WebUI/Views/ProductDetail/AddComment.cshtml
<!-- Add review -->
<form class="w-full" method="post" asp-action="AddComment" asp-controller="ProductDetail">
	<h5 class="mtext-108 cl2 p-b-7">
		Yorum Ekleyin
	</h5>

	<p class="stext-102 cl6">
		Yorumunuzun geçerli olması için aşağıdaki bilgileri eksiksiz giriniz.
	</p>

	<div class="flex-w flex-m p-t-50 p-b-23">
		<span class="stext-102 cl3 m-r-16">
			Puanınız
		</span>

		<span class="wrap-rating fs-18 cl11 pointer" id="rating-container">
			<i class="item-rating pointer zmdi zmdi-star-outline" data-value="1"></i>
			<i class="item-rating pointer zmdi zmdi-star-outline" data-value="2"></i>
			<i class="item-rating pointer zmdi zmdi-star-outline" data-value="3"></i>
			<i class="item-rating pointer zmdi zmdi-star-outline" data-value="4"></i>
			<i class="item-rating pointer zmdi zmdi-star-outline" data-value="5"></i>
			<input class="dis-none" type="number" name="Rating" id="rating" value="1">
		</span>

	</div>

	<div class="row p-b-25">


		<div class="col-sm-6 p-b-5">
			<label class="stext-102 cl3" for="name">Adınız Soyadınız</label>
			<input class="size-111 bor8 stext-102 cl2 p-lr-20" id="name" type="text" name="NameSurname">
		</div>

		<div class="col-sm-6 p-b-5">
			<label class="stext-102 cl3" for="email">Email</label>
			<input class="size-111 bor8 stext-102 cl2 p-lr-20" id="email" type="text" name="Email">
		</div>

		<div class="col-12 p-b-5">
			<label class="stext-102 cl3" for="review">Yorumunuz</label>
			<textarea class="size-110 bor8 stext-102 cl2 p-lr-20 p-tb-10" id="review" name="CommentDetail"></textarea>
		</div>

	</div>

	<input type="hidden" name="ProductId" value="@ViewBag.Id" />

	<button class="flex-c-m stext-101 cl0 size-112 bg7 bor11 hov-btn3 p-lr-15 trans-04 m-b-10">
		Kaydet
	</button>
</form>


<script>
	document.addEventListener("DOMContentLoaded", function () {
		const stars = document.querySelectorAll(".item-rating");
		const ratingInput = document.getElementById("rating");

		stars.forEach(star => {
			star.addEventListener("click", function () {
				const value = this.getAttribute("data-value");
				ratingInput.value = value;

				// Tüm yıldızları boşalt
				stars.forEach(s => s.classList.remove("zmdi-star", "cl11"));
				stars.forEach(s => s.classList.add("zmdi-star-outline"));

				// Seçili yıldızları doldur
				for (let i = 0; i < value; i++) {
					stars[i].classList.remove("zmdi-star-outline");
					stars[i].classList.add("zmdi-star", "cl11");
				}
			});
		});
	});
</script>

Frontends/ECommerce.WebUI/Views/ProductDetail/Index.cshtml
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/UILayout/_UILayout.cshtml";
}

<section class="sec-product-detail bg0 p-t-65 p-b-60">
	<div class="container">
		<div class="row">
			@* ürün detay modal'ındaki görsel slider *@
			@await Component.InvokeAsync("_ProductDetailImageSliderComponentPartial", new { id = ViewBag.Id })

			@* ürün detay modal'ındaki isim,fiyat, beden, renk gibi secenekler kısmı *@
			@await Component.InvokeAsync("_ProductDetailNameAndOtherInfo", new { id = ViewBag.Id })
		</div>

		@* Description, information vs. var *@
		<div class="bor10 m-t-50 p-t-43 p-b-40">
			<!-- Tab01 -->
			<div class="tab01">
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
					<li class="nav-item p-b-10">
						<a class="nav-link active" data-toggle="tab" href="#description" role="tab">Açıklama</a>
					</li>

					<li class="nav-item p-b-10">
						<a class="nav-link" data-toggle="tab" href="#information" role="tab">Ek Bilgiler</a>
					</li>

					<li class="nav-item p-b-10">
						<a class="nav-link" data-toggle="tab" href="#reviews" role="tab">Yorumlar</a>
					</li>
				</ul>

				<!-- Tab panes -->
				<div class="tab-content p-t-43">
					<!-- - -->
					@await Component.InvokeAsync("_ProductDetailDescriptionComponentPartial", new { id = ViewBag.Id })


					<!-- - -->
					@await Component.InvokeAsync("_ProductDetailInformationComponentPartial", new { id = ViewBag.Id })

					

					<!-- - -->
					@await Component.InvokeAsync("_ProductDetailReviewsComponentPartial", new { id = ViewBag.Id })

					

				</div>
			</div>
		</div>

	</div>

</section>




<!-- Related Products -->

@* ürün detayındaki en alttaki aynı kategorideki ürünler/benzer ürünler *@
@await Component.InvokeAsync("_SimilarProductsSameCategoryComponentPartial", new { id = ViewBag.Id })